version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db_data:/foo

volumes:
  db_data: